var retes = {
  "Name":"Alex",
  "Age":25,
  "Email":"alex@example.com",
  "Phone":"1234567890",
  "Address":"123 Main St, Anytown, USA",
  "City":"Anytown",
  "State":"CA",
  "Zip":"12345",
  "Country":"USA",
  "Gender":"Male",
  "Education":"Bachelor's Degree",
  "Occupation":"Software Engineer",
  "Interests":["Reading", "Traveling", "Coding"],
  "Skills":["Python", "JavaScript", "SQL"],
  "Languages":["English", "Spanish"],
  "Hobbies":["Reading", "Traveling", "Coding"],
  "Preferences":["Reading", "Traveling", "Coding"],
  'tutorial_1': {
    'title': 'Welcome to the app',
    'description': 'This is the first tutorial',
    'image': 'https://picsum.photos/200/300',
  },
  'tutorial_2': {
    'title': 'Welcome to the app',
    'description': 'This is the second tutorial',
    'image': 'https://picsum.photos/200/300',
  },
  
};
