// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATy7l4IIgxxZ0J7iFqQHLO9hCqIeh1CHs',
    appId: '1:361504801284:web:891ccdee6e7143f3c0ab51',
    messagingSenderId: '361504801284',
    projectId: 'flyconnect-ab4f2',
    authDomain: 'flyconnect-ab4f2.firebaseapp.com',
    databaseURL: 'https://flyconnect-ab4f2-default-rtdb.firebaseio.com',
    storageBucket: 'flyconnect-ab4f2.firebasestorage.app',
    measurementId: 'G-DBSSBSMEVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAViMZd_Vv4rrFjO5r_Jbd3wogHAOlOUzo',
    appId: '1:361504801284:android:7b9682e73d98c7fbc0ab51',
    messagingSenderId: '361504801284',
    projectId: 'flyconnect-ab4f2',
    databaseURL: 'https://flyconnect-ab4f2-default-rtdb.firebaseio.com',
    storageBucket: 'flyconnect-ab4f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZB1AEsY6kdadCX95Vbtx_titTYCSlO7g',
    appId: '1:361504801284:ios:8a69029e723e238dc0ab51',
    messagingSenderId: '361504801284',
    projectId: 'flyconnect-ab4f2',
    databaseURL: 'https://flyconnect-ab4f2-default-rtdb.firebaseio.com',
    storageBucket: 'flyconnect-ab4f2.firebasestorage.app',
    androidClientId: '361504801284-cf3lf5uuem6di00tf5300rbsse3ssfo2.apps.googleusercontent.com',
    iosClientId: '361504801284-7qg36av1juoccclkthio2c0bs12s8f35.apps.googleusercontent.com',
    iosBundleId: 'com.urbansyncinnovations.flyconnect',
  );
}
